/* This file was autogenerated from template version 0.0.0.2 and autogenerator version 0.0.0.1 */

#include "fc_serialization.h"

#ifdef __cplusplus
extern "C" {
#endif

uint32 PX4_VehicleCommandMsg_t_Enc(const PX4_VehicleCommandMsg_t *inObject, char *inOutBuffer, uint32 inSize)
{
	bool status = false;
	pb_ostream_t stream;

	px4_vehicle_command_msg_pb pbMsg;

    pbMsg.Confirmation = inObject->Confirmation;
    pbMsg.Timestamp = inObject->Timestamp;
    pbMsg.TargetComponent = inObject->TargetComponent;
    pbMsg.Param7 = inObject->Param7;
    pbMsg.Param6 = inObject->Param6;
    pbMsg.Param5 = inObject->Param5;
    pbMsg.Param4 = inObject->Param4;
    pbMsg.Param3 = inObject->Param3;
    pbMsg.Param2 = inObject->Param2;
    pbMsg.Param1 = inObject->Param1;
    pbMsg.TargetSystem = inObject->TargetSystem;
    pbMsg.SourceSystem = inObject->SourceSystem;
    pbMsg.Command = inObject->Command;
    pbMsg.SourceComponent = inObject->SourceComponent;

	/* Create a stream that will write to our buffer. */
	stream = pb_ostream_from_buffer((pb_byte_t *)inOutBuffer, inSize);
	
	/* Now we are ready to encode the message. */
	status = pb_encode(&stream, px4_vehicle_command_msg_pb_fields, &pbMsg);

	/* Check for errors... */
	if (!status)
	{
        OS_printf("Error encoding msg: %s", PB_GET_ERROR(&stream));
		return 0;
	}

	return stream.bytes_written;
}

uint32 PX4_VehicleCommandMsg_t_Dec(const char *inBuffer, uint32 inSize, PX4_VehicleCommandMsg_t *inOutObject)
{
	bool status = false;
	pb_istream_t stream;

	px4_vehicle_command_msg_pb pbMsg;

    /* Create a stream that reads from the buffer. */
	stream = pb_istream_from_buffer((const pb_byte_t *)inBuffer, inSize);

	/* Now we are ready to decode the message. */
	status = pb_decode(&stream, px4_vehicle_command_msg_pb_fields, &pbMsg); 

	/* Check for errors... */
	if (!status)
	{
        OS_printf("Error decoding msg: %s", PB_GET_ERROR(&stream));
		return 0;
	}

    inOutObject->Confirmation = pbMsg.Confirmation;
    inOutObject->Timestamp = pbMsg.Timestamp;
    inOutObject->TargetComponent = pbMsg.TargetComponent;
    inOutObject->Param7 = pbMsg.Param7;
    inOutObject->Param6 = pbMsg.Param6;
    inOutObject->Param5 = pbMsg.Param5;
    inOutObject->Param4 = pbMsg.Param4;
    inOutObject->Param3 = pbMsg.Param3;
    inOutObject->Param2 = pbMsg.Param2;
    inOutObject->Param1 = pbMsg.Param1;
    inOutObject->TargetSystem = pbMsg.TargetSystem;
    inOutObject->SourceSystem = pbMsg.SourceSystem;
    inOutObject->Command = pbMsg.Command;
    inOutObject->SourceComponent = pbMsg.SourceComponent;

	return sizeof(PX4_VehicleCommandMsg_t);
}


uint32 PX4_PositionSetpointTripletMsg_t_Enc(const PX4_PositionSetpointTripletMsg_t *inObject, char *inOutBuffer, uint32 inSize)
{
	bool status = false;
	pb_ostream_t stream;

	px4_position_setpoint_triplet_pb pbMsg;

    pbMsg.Timestamp = inObject->Timestamp;
    pbMsg.Current.AccelerationIsForce = inObject->Current.AccelerationIsForce;
    pbMsg.Current.DisableMcYawControl = inObject->Current.DisableMcYawControl;
    pbMsg.Current.Yaw = inObject->Current.Yaw;
    pbMsg.Current.Lon = inObject->Current.Lon;
    pbMsg.Current.PitchMin = inObject->Current.PitchMin;
    pbMsg.Current.VX = inObject->Current.VX;
    pbMsg.Current.Valid = inObject->Current.Valid;
    pbMsg.Current.AY = inObject->Current.AY;
    pbMsg.Current.YawValid = inObject->Current.YawValid;
    pbMsg.Current.X = inObject->Current.X;
    pbMsg.Current.VY = inObject->Current.VY;
    pbMsg.Current.PositionValid = inObject->Current.PositionValid;
    pbMsg.Current.Yawspeed = inObject->Current.Yawspeed;
    pbMsg.Current.VelocityValid = inObject->Current.VelocityValid;
    pbMsg.Current.Type = inObject->Current.Type;
    pbMsg.Current.Z = inObject->Current.Z;
    pbMsg.Current.CruisingThrottle = inObject->Current.CruisingThrottle;
    pbMsg.Current.Lat = inObject->Current.Lat;
    pbMsg.Current.YawspeedValid = inObject->Current.YawspeedValid;
    pbMsg.Current.CruisingSpeed = inObject->Current.CruisingSpeed;
    pbMsg.Current.AcceptanceRadius = inObject->Current.AcceptanceRadius;
    pbMsg.Current.LoiterDirection = inObject->Current.LoiterDirection;
    pbMsg.Current.Y = inObject->Current.Y;
    pbMsg.Current.AX = inObject->Current.AX;
    pbMsg.Current.VZ = inObject->Current.VZ;
    pbMsg.Current.AZ = inObject->Current.AZ;
    pbMsg.Current.AccelerationValid = inObject->Current.AccelerationValid;
    pbMsg.Current.LoiterRadius = inObject->Current.LoiterRadius;
    pbMsg.Current.Alt = inObject->Current.Alt;
    pbMsg.Next.AccelerationIsForce = inObject->Next.AccelerationIsForce;
    pbMsg.Next.DisableMcYawControl = inObject->Next.DisableMcYawControl;
    pbMsg.Next.Yaw = inObject->Next.Yaw;
    pbMsg.Next.Lon = inObject->Next.Lon;
    pbMsg.Next.PitchMin = inObject->Next.PitchMin;
    pbMsg.Next.VX = inObject->Next.VX;
    pbMsg.Next.Valid = inObject->Next.Valid;
    pbMsg.Next.AY = inObject->Next.AY;
    pbMsg.Next.YawValid = inObject->Next.YawValid;
    pbMsg.Next.X = inObject->Next.X;
    pbMsg.Next.VY = inObject->Next.VY;
    pbMsg.Next.PositionValid = inObject->Next.PositionValid;
    pbMsg.Next.Yawspeed = inObject->Next.Yawspeed;
    pbMsg.Next.VelocityValid = inObject->Next.VelocityValid;
    pbMsg.Next.Type = inObject->Next.Type;
    pbMsg.Next.Z = inObject->Next.Z;
    pbMsg.Next.CruisingThrottle = inObject->Next.CruisingThrottle;
    pbMsg.Next.Lat = inObject->Next.Lat;
    pbMsg.Next.YawspeedValid = inObject->Next.YawspeedValid;
    pbMsg.Next.CruisingSpeed = inObject->Next.CruisingSpeed;
    pbMsg.Next.AcceptanceRadius = inObject->Next.AcceptanceRadius;
    pbMsg.Next.LoiterDirection = inObject->Next.LoiterDirection;
    pbMsg.Next.Y = inObject->Next.Y;
    pbMsg.Next.AX = inObject->Next.AX;
    pbMsg.Next.VZ = inObject->Next.VZ;
    pbMsg.Next.AZ = inObject->Next.AZ;
    pbMsg.Next.AccelerationValid = inObject->Next.AccelerationValid;
    pbMsg.Next.LoiterRadius = inObject->Next.LoiterRadius;
    pbMsg.Next.Alt = inObject->Next.Alt;
    pbMsg.Previous.AccelerationIsForce = inObject->Previous.AccelerationIsForce;
    pbMsg.Previous.DisableMcYawControl = inObject->Previous.DisableMcYawControl;
    pbMsg.Previous.Yaw = inObject->Previous.Yaw;
    pbMsg.Previous.Lon = inObject->Previous.Lon;
    pbMsg.Previous.PitchMin = inObject->Previous.PitchMin;
    pbMsg.Previous.VX = inObject->Previous.VX;
    pbMsg.Previous.Valid = inObject->Previous.Valid;
    pbMsg.Previous.AY = inObject->Previous.AY;
    pbMsg.Previous.YawValid = inObject->Previous.YawValid;
    pbMsg.Previous.X = inObject->Previous.X;
    pbMsg.Previous.VY = inObject->Previous.VY;
    pbMsg.Previous.PositionValid = inObject->Previous.PositionValid;
    pbMsg.Previous.Yawspeed = inObject->Previous.Yawspeed;
    pbMsg.Previous.VelocityValid = inObject->Previous.VelocityValid;
    pbMsg.Previous.Type = inObject->Previous.Type;
    pbMsg.Previous.Z = inObject->Previous.Z;
    pbMsg.Previous.CruisingThrottle = inObject->Previous.CruisingThrottle;
    pbMsg.Previous.Lat = inObject->Previous.Lat;
    pbMsg.Previous.YawspeedValid = inObject->Previous.YawspeedValid;
    pbMsg.Previous.CruisingSpeed = inObject->Previous.CruisingSpeed;
    pbMsg.Previous.AcceptanceRadius = inObject->Previous.AcceptanceRadius;
    pbMsg.Previous.LoiterDirection = inObject->Previous.LoiterDirection;
    pbMsg.Previous.Y = inObject->Previous.Y;
    pbMsg.Previous.AX = inObject->Previous.AX;
    pbMsg.Previous.VZ = inObject->Previous.VZ;
    pbMsg.Previous.AZ = inObject->Previous.AZ;
    pbMsg.Previous.AccelerationValid = inObject->Previous.AccelerationValid;
    pbMsg.Previous.LoiterRadius = inObject->Previous.LoiterRadius;
    pbMsg.Previous.Alt = inObject->Previous.Alt;

	/* Create a stream that will write to our buffer. */
	stream = pb_ostream_from_buffer((pb_byte_t *)inOutBuffer, inSize);
	
	/* Now we are ready to encode the message. */
	status = pb_encode(&stream, px4_position_setpoint_triplet_pb_fields, &pbMsg);

	/* Check for errors... */
	if (!status)
	{
        OS_printf("Error encoding msg: %s", PB_GET_ERROR(&stream));
		return 0;
	}

	return stream.bytes_written;
}

uint32 PX4_PositionSetpointTripletMsg_t_Dec(const char *inBuffer, uint32 inSize, PX4_PositionSetpointTripletMsg_t *inOutObject)
{
	bool status = false;
	pb_istream_t stream;

	px4_position_setpoint_triplet_pb pbMsg;

    /* Create a stream that reads from the buffer. */
	stream = pb_istream_from_buffer((const pb_byte_t *)inBuffer, inSize);

	/* Now we are ready to decode the message. */
	status = pb_decode(&stream, px4_position_setpoint_triplet_pb_fields, &pbMsg); 

	/* Check for errors... */
	if (!status)
	{
        OS_printf("Error decoding msg: %s", PB_GET_ERROR(&stream));
		return 0;
	}

    inOutObject->Timestamp = pbMsg.Timestamp;
/*    inOutObject->Previous.Timestamp = PX4LIB_GetPX4TimeUs();*/
/*    inOutObject->Current.Timestamp = PX4LIB_GetPX4TimeUs();*/
/*    inOutObject->Next.Timestamp = PX4LIB_GetPX4TimeUs();*/
    inOutObject->Current.AccelerationIsForce = pbMsg.Current.AccelerationIsForce;
    inOutObject->Current.DisableMcYawControl = pbMsg.Current.DisableMcYawControl;
    inOutObject->Current.Yaw = pbMsg.Current.Yaw;
    inOutObject->Current.Lon = pbMsg.Current.Lon;
    inOutObject->Current.PitchMin = pbMsg.Current.PitchMin;
    inOutObject->Current.VX = pbMsg.Current.VX;
    inOutObject->Current.Valid = pbMsg.Current.Valid;
    inOutObject->Current.AY = pbMsg.Current.AY;
    inOutObject->Current.YawValid = pbMsg.Current.YawValid;
    inOutObject->Current.X = pbMsg.Current.X;
    inOutObject->Current.VY = pbMsg.Current.VY;
    inOutObject->Current.PositionValid = pbMsg.Current.PositionValid;
    inOutObject->Current.Yawspeed = pbMsg.Current.Yawspeed;
    inOutObject->Current.VelocityValid = pbMsg.Current.VelocityValid;
    inOutObject->Current.Type = pbMsg.Current.Type;
    inOutObject->Current.Z = pbMsg.Current.Z;
    inOutObject->Current.CruisingThrottle = pbMsg.Current.CruisingThrottle;
    inOutObject->Current.Lat = pbMsg.Current.Lat;
    inOutObject->Current.YawspeedValid = pbMsg.Current.YawspeedValid;
    inOutObject->Current.CruisingSpeed = pbMsg.Current.CruisingSpeed;
    inOutObject->Current.AcceptanceRadius = pbMsg.Current.AcceptanceRadius;
    inOutObject->Current.LoiterDirection = pbMsg.Current.LoiterDirection;
    inOutObject->Current.Y = pbMsg.Current.Y;
    inOutObject->Current.AX = pbMsg.Current.AX;
    inOutObject->Current.VZ = pbMsg.Current.VZ;
    inOutObject->Current.AZ = pbMsg.Current.AZ;
    inOutObject->Current.AccelerationValid = pbMsg.Current.AccelerationValid;
    inOutObject->Current.LoiterRadius = pbMsg.Current.LoiterRadius;
    inOutObject->Current.Alt = pbMsg.Current.Alt;
    inOutObject->Next.AccelerationIsForce = pbMsg.Next.AccelerationIsForce;
    inOutObject->Next.DisableMcYawControl = pbMsg.Next.DisableMcYawControl;
    inOutObject->Next.Yaw = pbMsg.Next.Yaw;
    inOutObject->Next.Lon = pbMsg.Next.Lon;
    inOutObject->Next.PitchMin = pbMsg.Next.PitchMin;
    inOutObject->Next.VX = pbMsg.Next.VX;
    inOutObject->Next.Valid = pbMsg.Next.Valid;
    inOutObject->Next.AY = pbMsg.Next.AY;
    inOutObject->Next.YawValid = pbMsg.Next.YawValid;
    inOutObject->Next.X = pbMsg.Next.X;
    inOutObject->Next.VY = pbMsg.Next.VY;
    inOutObject->Next.PositionValid = pbMsg.Next.PositionValid;
    inOutObject->Next.Yawspeed = pbMsg.Next.Yawspeed;
    inOutObject->Next.VelocityValid = pbMsg.Next.VelocityValid;
    inOutObject->Next.Type = pbMsg.Next.Type;
    inOutObject->Next.Z = pbMsg.Next.Z;
    inOutObject->Next.CruisingThrottle = pbMsg.Next.CruisingThrottle;
    inOutObject->Next.Lat = pbMsg.Next.Lat;
    inOutObject->Next.YawspeedValid = pbMsg.Next.YawspeedValid;
    inOutObject->Next.CruisingSpeed = pbMsg.Next.CruisingSpeed;
    inOutObject->Next.AcceptanceRadius = pbMsg.Next.AcceptanceRadius;
    inOutObject->Next.LoiterDirection = pbMsg.Next.LoiterDirection;
    inOutObject->Next.Y = pbMsg.Next.Y;
    inOutObject->Next.AX = pbMsg.Next.AX;
    inOutObject->Next.VZ = pbMsg.Next.VZ;
    inOutObject->Next.AZ = pbMsg.Next.AZ;
    inOutObject->Next.AccelerationValid = pbMsg.Next.AccelerationValid;
    inOutObject->Next.LoiterRadius = pbMsg.Next.LoiterRadius;
    inOutObject->Next.Alt = pbMsg.Next.Alt;
    inOutObject->Previous.AccelerationIsForce = pbMsg.Previous.AccelerationIsForce;
    inOutObject->Previous.DisableMcYawControl = pbMsg.Previous.DisableMcYawControl;
    inOutObject->Previous.Yaw = pbMsg.Previous.Yaw;
    inOutObject->Previous.Lon = pbMsg.Previous.Lon;
    inOutObject->Previous.PitchMin = pbMsg.Previous.PitchMin;
    inOutObject->Previous.VX = pbMsg.Previous.VX;
    inOutObject->Previous.Valid = pbMsg.Previous.Valid;
    inOutObject->Previous.AY = pbMsg.Previous.AY;
    inOutObject->Previous.YawValid = pbMsg.Previous.YawValid;
    inOutObject->Previous.X = pbMsg.Previous.X;
    inOutObject->Previous.VY = pbMsg.Previous.VY;
    inOutObject->Previous.PositionValid = pbMsg.Previous.PositionValid;
    inOutObject->Previous.Yawspeed = pbMsg.Previous.Yawspeed;
    inOutObject->Previous.VelocityValid = pbMsg.Previous.VelocityValid;
    inOutObject->Previous.Type = pbMsg.Previous.Type;
    inOutObject->Previous.Z = pbMsg.Previous.Z;
    inOutObject->Previous.CruisingThrottle = pbMsg.Previous.CruisingThrottle;
    inOutObject->Previous.Lat = pbMsg.Previous.Lat;
    inOutObject->Previous.YawspeedValid = pbMsg.Previous.YawspeedValid;
    inOutObject->Previous.CruisingSpeed = pbMsg.Previous.CruisingSpeed;
    inOutObject->Previous.AcceptanceRadius = pbMsg.Previous.AcceptanceRadius;
    inOutObject->Previous.LoiterDirection = pbMsg.Previous.LoiterDirection;
    inOutObject->Previous.Y = pbMsg.Previous.Y;
    inOutObject->Previous.AX = pbMsg.Previous.AX;
    inOutObject->Previous.VZ = pbMsg.Previous.VZ;
    inOutObject->Previous.AZ = pbMsg.Previous.AZ;
    inOutObject->Previous.AccelerationValid = pbMsg.Previous.AccelerationValid;
    inOutObject->Previous.LoiterRadius = pbMsg.Previous.LoiterRadius;
    inOutObject->Previous.Alt = pbMsg.Previous.Alt;

	return sizeof(PX4_PositionSetpointTripletMsg_t);
}


uint32 PX4_VehicleGlobalPositionMsg_t_Enc(const PX4_VehicleGlobalPositionMsg_t *inObject, char *inOutBuffer, uint32 inSize)
{
	bool status = false;
	pb_ostream_t stream;

	px4_vehicle_global_position_msg_pb pbMsg;

    pbMsg.EvH = inObject->EvH;
    pbMsg.AltResetCounter = inObject->AltResetCounter;
    pbMsg.VelN = inObject->VelN;
    pbMsg.VelD = inObject->VelD;
    pbMsg.DeadReckoning = inObject->DeadReckoning;
    pbMsg.DeltaAlt = inObject->DeltaAlt;
    pbMsg.TimeUtcUsec = inObject->TimeUtcUsec;
    pbMsg.Timestamp = inObject->Timestamp;
    pbMsg.VelE = inObject->VelE;
    /* Unroll indexes */
    pbMsg.DeltaLatLon_count = 2;
    pbMsg.DeltaLatLon[0] = inObject->DeltaLatLon[0];
    pbMsg.DeltaLatLon[1] = inObject->DeltaLatLon[1];
    pbMsg.Lon = inObject->Lon;
    pbMsg.TerrainAlt = inObject->TerrainAlt;
    pbMsg.TerrainAltValid = inObject->TerrainAltValid;
    pbMsg.EpV = inObject->EpV;
    pbMsg.LatLonResetCounter = inObject->LatLonResetCounter;
    pbMsg.EpH = inObject->EpH;
    pbMsg.PressureAlt = inObject->PressureAlt;
    pbMsg.Lat = inObject->Lat;
    pbMsg.Alt = inObject->Alt;
    pbMsg.Yaw = inObject->Yaw;
    pbMsg.EvV = inObject->EvV;

	/* Create a stream that will write to our buffer. */
	stream = pb_ostream_from_buffer((pb_byte_t *)inOutBuffer, inSize);
	
	/* Now we are ready to encode the message. */
	status = pb_encode(&stream, px4_vehicle_global_position_msg_pb_fields, &pbMsg);

	/* Check for errors... */
	if (!status)
	{
        OS_printf("Error encoding msg: %s", PB_GET_ERROR(&stream));
		return 0;
	}

	return stream.bytes_written;
}

uint32 PX4_VehicleGlobalPositionMsg_t_Dec(const char *inBuffer, uint32 inSize, PX4_VehicleGlobalPositionMsg_t *inOutObject)
{
	bool status = false;
	pb_istream_t stream;

	px4_vehicle_global_position_msg_pb pbMsg;

    /* Create a stream that reads from the buffer. */
	stream = pb_istream_from_buffer((const pb_byte_t *)inBuffer, inSize);

	/* Now we are ready to decode the message. */
	status = pb_decode(&stream, px4_vehicle_global_position_msg_pb_fields, &pbMsg); 

	/* Check for errors... */
	if (!status)
	{
        OS_printf("Error decoding msg: %s", PB_GET_ERROR(&stream));
		return 0;
	}

    inOutObject->EvH = pbMsg.EvH;
    inOutObject->AltResetCounter = pbMsg.AltResetCounter;
    inOutObject->VelN = pbMsg.VelN;
    inOutObject->VelD = pbMsg.VelD;
    inOutObject->DeadReckoning = pbMsg.DeadReckoning;
    inOutObject->DeltaAlt = pbMsg.DeltaAlt;
    inOutObject->TimeUtcUsec = pbMsg.TimeUtcUsec;
    inOutObject->Timestamp = pbMsg.Timestamp;
    inOutObject->VelE = pbMsg.VelE;
    /* Unroll indexes */
    inOutObject->DeltaLatLon[0] = pbMsg.DeltaLatLon[0];
    inOutObject->DeltaLatLon[1] = pbMsg.DeltaLatLon[1];
    inOutObject->Lon = pbMsg.Lon;
    inOutObject->TerrainAlt = pbMsg.TerrainAlt;
    inOutObject->TerrainAltValid = pbMsg.TerrainAltValid;
    inOutObject->EpV = pbMsg.EpV;
    inOutObject->LatLonResetCounter = pbMsg.LatLonResetCounter;
    inOutObject->EpH = pbMsg.EpH;
    inOutObject->PressureAlt = pbMsg.PressureAlt;
    inOutObject->Lat = pbMsg.Lat;
    inOutObject->Alt = pbMsg.Alt;
    inOutObject->Yaw = pbMsg.Yaw;
    inOutObject->EvV = pbMsg.EvV;

	return sizeof(PX4_VehicleGlobalPositionMsg_t);
}


uint32 PX4_ManualControlSetpointMsg_t_Enc(const PX4_ManualControlSetpointMsg_t *inObject, char *inOutBuffer, uint32 inSize)
{
	bool status = false;
	pb_ostream_t stream;

	px4_manual_control_setpoint_pb pbMsg;

    pbMsg.ModeSlot = inObject->ModeSlot;
    pbMsg.Timestamp = inObject->Timestamp;
    pbMsg.KillSwitch = inObject->KillSwitch;
    pbMsg.ArmSwitch = inObject->ArmSwitch;
    pbMsg.ManSwitch = inObject->ManSwitch;
    pbMsg.ModeSwitch = inObject->ModeSwitch;
    pbMsg.LoiterSwitch = inObject->LoiterSwitch;
    pbMsg.ReturnSwitch = inObject->ReturnSwitch;
    pbMsg.RattitudeSwitch = inObject->RattitudeSwitch;
    pbMsg.PosctlSwitch = inObject->PosctlSwitch;
    pbMsg.TransitionSwitch = inObject->TransitionSwitch;
    pbMsg.R = inObject->R;
    pbMsg.Flaps = inObject->Flaps;
    pbMsg.Y = inObject->Y;
    pbMsg.X = inObject->X;
    pbMsg.Z = inObject->Z;
    pbMsg.OffboardSwitch = inObject->OffboardSwitch;
    pbMsg.GearSwitch = inObject->GearSwitch;
    pbMsg.StabSwitch = inObject->StabSwitch;
    pbMsg.AcroSwitch = inObject->AcroSwitch;
    pbMsg.DataSource = inObject->DataSource;
    pbMsg.Aux2 = inObject->Aux2;
    pbMsg.Aux3 = inObject->Aux3;
    pbMsg.Aux1 = inObject->Aux1;
    pbMsg.Aux4 = inObject->Aux4;
    pbMsg.Aux5 = inObject->Aux5;

	/* Create a stream that will write to our buffer. */
	stream = pb_ostream_from_buffer((pb_byte_t *)inOutBuffer, inSize);
	
	/* Now we are ready to encode the message. */
	status = pb_encode(&stream, px4_manual_control_setpoint_pb_fields, &pbMsg);

	/* Check for errors... */
	if (!status)
	{
        OS_printf("Error encoding msg: %s", PB_GET_ERROR(&stream));
		return 0;
	}

	return stream.bytes_written;
}

uint32 PX4_ManualControlSetpointMsg_t_Dec(const char *inBuffer, uint32 inSize, PX4_ManualControlSetpointMsg_t *inOutObject)
{
	bool status = false;
	pb_istream_t stream;

	px4_manual_control_setpoint_pb pbMsg;

    /* Create a stream that reads from the buffer. */
	stream = pb_istream_from_buffer((const pb_byte_t *)inBuffer, inSize);

	/* Now we are ready to decode the message. */
	status = pb_decode(&stream, px4_manual_control_setpoint_pb_fields, &pbMsg); 

	/* Check for errors... */
	if (!status)
	{
        OS_printf("Error decoding msg: %s", PB_GET_ERROR(&stream));
		return 0;
	}

    inOutObject->ModeSlot = pbMsg.ModeSlot;
    inOutObject->Timestamp = pbMsg.Timestamp;
    inOutObject->KillSwitch = pbMsg.KillSwitch;
    inOutObject->ArmSwitch = pbMsg.ArmSwitch;
    inOutObject->ManSwitch = pbMsg.ManSwitch;
    inOutObject->ModeSwitch = pbMsg.ModeSwitch;
    inOutObject->LoiterSwitch = pbMsg.LoiterSwitch;
    inOutObject->ReturnSwitch = pbMsg.ReturnSwitch;
    inOutObject->RattitudeSwitch = pbMsg.RattitudeSwitch;
    inOutObject->PosctlSwitch = pbMsg.PosctlSwitch;
    inOutObject->TransitionSwitch = pbMsg.TransitionSwitch;
    inOutObject->R = pbMsg.R;
    inOutObject->Flaps = pbMsg.Flaps;
    inOutObject->Y = pbMsg.Y;
    inOutObject->X = pbMsg.X;
    inOutObject->Z = pbMsg.Z;
    inOutObject->OffboardSwitch = pbMsg.OffboardSwitch;
    inOutObject->GearSwitch = pbMsg.GearSwitch;
    inOutObject->StabSwitch = pbMsg.StabSwitch;
    inOutObject->AcroSwitch = pbMsg.AcroSwitch;
    inOutObject->DataSource = pbMsg.DataSource;
    inOutObject->Aux2 = pbMsg.Aux2;
    inOutObject->Aux3 = pbMsg.Aux3;
    inOutObject->Aux1 = pbMsg.Aux1;
    inOutObject->Aux4 = pbMsg.Aux4;
    inOutObject->Aux5 = pbMsg.Aux5;

	return sizeof(PX4_ManualControlSetpointMsg_t);
}


#ifdef __cplusplus
} /* extern "C" */
#endif
